"""add_portfolio_trades

Revision ID: 1421559f80c0
Revises: 4ba13df3e863
Create Date: 2026-08-04 18:39:34.464133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1421559f80c0'
down_revision: Union[str, Sequence[str], None] = '4ba13df3e863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price_per_share', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('fees', sa.Float(), nullable=False),
    sa.Column('traded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('eur_amount', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio_trades', schema=None) as batch_op:
        batch_op.create_index('ix_portfolio_trades_ticker', ['ticker'], unique=False)
        batch_op.create_index('ix_portfolio_trades_traded_at', ['traded_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_trades', schema=None) as batch_op:
        batch_op.drop_index('ix_portfolio_trades_traded_at')
        batch_op.drop_index('ix_portfolio_trades_ticker')

    op.drop_table('portfolio_trades')
    # ### end Alembic commands ###
