"""drop_market_snapshots_table

Revision ID: 4ba13df3e863
Revises: 6d0daadedcd3
Create Date: 2026-08-04 17:52:44.308184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ba13df3e863'
down_revision: Union[str, Sequence[str], None] = '6d0daadedcd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_snapshot_ticker_at'))

    op.drop_table('market_snapshots')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_snapshots',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ticker', sa.VARCHAR(length=16), nullable=False),
    sa.Column('snapshot_at', sa.DATETIME(), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=True),
    sa.Column('volume', sa.INTEGER(), nullable=True),
    sa.Column('atr_14', sa.FLOAT(), nullable=True),
    sa.Column('return_5d', sa.FLOAT(), nullable=True),
    sa.Column('return_21d', sa.FLOAT(), nullable=True),
    sa.Column('return_63d', sa.FLOAT(), nullable=True),
    sa.Column('dist_to_ma20', sa.FLOAT(), nullable=True),
    sa.Column('dist_to_ma50', sa.FLOAT(), nullable=True),
    sa.Column('dist_to_ma200', sa.FLOAT(), nullable=True),
    sa.Column('rsi_14', sa.FLOAT(), nullable=True),
    sa.Column('volume_ratio_20', sa.FLOAT(), nullable=True),
    sa.Column('spy_return_21d', sa.FLOAT(), nullable=True),
    sa.Column('computed_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'snapshot_at', name=op.f('uq_snapshot_ticker_at'))
    )
    with op.batch_alter_table('market_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_snapshot_ticker_at'), ['ticker', 'snapshot_at'], unique=False)

    # ### end Alembic commands ###
