"""add_lens_snapshots_and_outcomes

Revision ID: 6d0daadedcd3
Revises: 97889a067fc2
Create Date: 2026-05-08 15:07:10.057144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d0daadedcd3'
down_revision: Union[str, Sequence[str], None] = '97889a067fc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lens_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('lens_name', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('conviction', sa.String(length=8), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('points_json', sa.Text(), nullable=False),
    sa.Column('sources_used', sa.Text(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['research_plans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'as_of', 'mode', 'lens_name', name='uq_lens_snapshot_run')
    )
    with op.batch_alter_table('lens_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lens_snapshots_as_of'), ['as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_lens_snapshots_lens_name'), ['lens_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_lens_snapshots_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lens_snapshots_ticker'), ['ticker'], unique=False)

    op.create_table('lens_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('horizon', sa.String(length=8), nullable=False),
    sa.Column('return_pct', sa.Float(), nullable=False),
    sa.Column('excess_vs_spy_pct', sa.Float(), nullable=False),
    sa.Column('direction_correct', sa.Boolean(), nullable=False),
    sa.Column('regime', sa.String(length=8), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['lens_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'horizon', name='uq_lens_outcome_horizon')
    )
    with op.batch_alter_table('lens_outcomes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lens_outcomes_snapshot_id'), ['snapshot_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lens_outcomes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lens_outcomes_snapshot_id'))

    op.drop_table('lens_outcomes')
    with op.batch_alter_table('lens_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lens_snapshots_ticker'))
        batch_op.drop_index(batch_op.f('ix_lens_snapshots_plan_id'))
        batch_op.drop_index(batch_op.f('ix_lens_snapshots_lens_name'))
        batch_op.drop_index(batch_op.f('ix_lens_snapshots_as_of'))

    op.drop_table('lens_snapshots')
    # ### end Alembic commands ###
