"""baseline_existing_schema

Revision ID: be68ca021077
Revises: 
Create Date: 2026-05-08 12:37:15.154202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be68ca021077'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('annotations', schema=None) as batch_op:
        batch_op.create_index('ix_annotation_entity', ['entity_type', 'entity_id'], unique=False)

    op.create_table('creators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('primary_source_type', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('display_name')
    )
    op.create_table('market_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('atr_14', sa.Float(), nullable=True),
    sa.Column('return_5d', sa.Float(), nullable=True),
    sa.Column('return_21d', sa.Float(), nullable=True),
    sa.Column('return_63d', sa.Float(), nullable=True),
    sa.Column('dist_to_ma20', sa.Float(), nullable=True),
    sa.Column('dist_to_ma50', sa.Float(), nullable=True),
    sa.Column('dist_to_ma200', sa.Float(), nullable=True),
    sa.Column('rsi_14', sa.Float(), nullable=True),
    sa.Column('volume_ratio_20', sa.Float(), nullable=True),
    sa.Column('spy_return_21d', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'snapshot_at', name='uq_snapshot_ticker_at')
    )
    with op.batch_alter_table('market_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_snapshot_ticker_at', ['ticker', 'snapshot_at'], unique=False)

    op.create_table('research_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('day_key', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.String(length=8), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('plan_json', sa.Text(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_plans', schema=None) as batch_op:
        batch_op.create_index('ix_research_plan_ticker_mode_day', ['ticker', 'mode', 'day_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_plans_ticker'), ['ticker'], unique=False)

    op.create_table('research_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('status_confidence', sa.String(length=8), nullable=False),
    sa.Column('setup_type', sa.String(length=32), nullable=False),
    sa.Column('setup_confidence', sa.String(length=8), nullable=False),
    sa.Column('primary_style', sa.String(length=40), nullable=True),
    sa.Column('last_close', sa.Float(), nullable=True),
    sa.Column('pct_off_52w_high', sa.Float(), nullable=True),
    sa.Column('return_5d', sa.Float(), nullable=True),
    sa.Column('return_21d', sa.Float(), nullable=True),
    sa.Column('return_63d', sa.Float(), nullable=True),
    sa.Column('ma_alignment', sa.String(length=20), nullable=False),
    sa.Column('rsi_14', sa.Float(), nullable=True),
    sa.Column('atr_14_pct', sa.Float(), nullable=True),
    sa.Column('sma_50_slope_21d_pct', sa.Float(), nullable=True),
    sa.Column('relative_strength_vs_spy_63d', sa.Float(), nullable=True),
    sa.Column('nearest_support', sa.Float(), nullable=True),
    sa.Column('nearest_resistance', sa.Float(), nullable=True),
    sa.Column('pullback_pct_from_recent_high', sa.Float(), nullable=True),
    sa.Column('breakout_distance_pct', sa.Float(), nullable=True),
    sa.Column('entry_zone_available', sa.Boolean(), nullable=False),
    sa.Column('entry_trigger', sa.Float(), nullable=True),
    sa.Column('entry_zone_low', sa.Float(), nullable=True),
    sa.Column('entry_zone_high', sa.Float(), nullable=True),
    sa.Column('invalidation_reference', sa.Float(), nullable=True),
    sa.Column('risk_reward_estimate', sa.Float(), nullable=True),
    sa.Column('transcript_n_calls', sa.Integer(), nullable=False),
    sa.Column('transcript_n_claims', sa.Integer(), nullable=False),
    sa.Column('transcript_n_creators', sa.Integer(), nullable=False),
    sa.Column('transcript_polarity_30d', sa.Float(), nullable=True),
    sa.Column('transcript_coverage_status', sa.String(length=20), nullable=True),
    sa.Column('transcript_confirms', sa.String(length=16), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_research_snapshot_status', ['status'], unique=False)
        batch_op.create_index('ix_research_snapshot_ticker_time', ['ticker', 'as_of'], unique=False)

    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', 'label', name='uq_tag_entity_label')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index('ix_tag_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('ix_tag_label', ['label'], unique=False)

    op.create_table('ticker_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_size', sa.String(length=8), nullable=False),
    sa.Column('signal_type', sa.String(length=32), nullable=False),
    sa.Column('n_mentions', sa.Integer(), nullable=False),
    sa.Column('n_distinct_creators', sa.Integer(), nullable=False),
    sa.Column('n_documents', sa.Integer(), nullable=False),
    sa.Column('net_polarity', sa.Float(), nullable=True),
    sa.Column('credibility_weighted_polarity', sa.Float(), nullable=True),
    sa.Column('avg_entry_distance_pct', sa.Float(), nullable=True),
    sa.Column('avg_target_distance_pct', sa.Float(), nullable=True),
    sa.Column('avg_stop_distance_pct', sa.Float(), nullable=True),
    sa.Column('n_factual', sa.Integer(), nullable=False),
    sa.Column('n_opinion', sa.Integer(), nullable=False),
    sa.Column('n_speculation', sa.Integer(), nullable=False),
    sa.Column('n_hype', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('aggregator_version', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'window_end', 'window_size', 'signal_type', name='uq_ticker_signal_natural_key')
    )
    with op.batch_alter_table('ticker_signals', schema=None) as batch_op:
        batch_op.create_index('ix_ticker_signal_lookup', ['ticker', 'window_end'], unique=False)
        batch_op.create_index('ix_ticker_signal_type_window', ['signal_type', 'window_size'], unique=False)

    op.create_table('walkforward_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_name', sa.String(length=64), nullable=False),
    sa.Column('strategy_version', sa.String(length=32), nullable=False),
    sa.Column('config_hash', sa.String(length=32), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rebalance_mode', sa.String(length=16), nullable=False),
    sa.Column('cost_bps', sa.Integer(), nullable=False),
    sa.Column('benchmark_ticker', sa.String(length=16), nullable=False),
    sa.Column('n_rebalances', sa.Integer(), nullable=False),
    sa.Column('n_trades', sa.Integer(), nullable=False),
    sa.Column('underpowered', sa.Boolean(), nullable=False),
    sa.Column('cagr', sa.Float(), nullable=True),
    sa.Column('sharpe', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('annualized_vol', sa.Float(), nullable=True),
    sa.Column('hit_rate', sa.Float(), nullable=True),
    sa.Column('hit_rate_lower_ci', sa.Float(), nullable=True),
    sa.Column('hit_rate_upper_ci', sa.Float(), nullable=True),
    sa.Column('benchmark_cagr', sa.Float(), nullable=True),
    sa.Column('excess_cagr', sa.Float(), nullable=True),
    sa.Column('avg_holding_days', sa.Float(), nullable=True),
    sa.Column('win_loss_ratio', sa.Float(), nullable=True),
    sa.Column('turnover', sa.Float(), nullable=True),
    sa.Column('metrics_json', sa.Text(), nullable=False),
    sa.Column('trades_json', sa.Text(), nullable=False),
    sa.Column('equity_curve_json', sa.Text(), nullable=False),
    sa.Column('sanity_checks_json', sa.Text(), nullable=False),
    sa.Column('warnings_json', sa.Text(), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('brier_score', sa.Float(), nullable=True),
    sa.Column('reliability_json', sa.Text(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_name', 'strategy_version', 'config_hash', name='uq_walkforward_natural_key')
    )
    with op.batch_alter_table('walkforward_results', schema=None) as batch_op:
        batch_op.create_index('ix_walkforward_strategy', ['strategy_name', 'strategy_version'], unique=False)

    op.create_table('watchlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('note', sa.String(length=256), nullable=True),
    sa.Column('pinned_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', name='uq_watchlist_entity')
    )
    op.create_table('creator_scorecards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('window_label', sa.String(length=16), nullable=False),
    sa.Column('horizon', sa.String(length=8), nullable=False),
    sa.Column('n_calls', sa.Integer(), nullable=False),
    sa.Column('n_activated', sa.Integer(), nullable=False),
    sa.Column('n_unique_tickers', sa.Integer(), nullable=False),
    sa.Column('activation_rate', sa.Float(), nullable=True),
    sa.Column('hit_rate', sa.Float(), nullable=True),
    sa.Column('hit_rate_lower_ci', sa.Float(), nullable=True),
    sa.Column('hit_rate_upper_ci', sa.Float(), nullable=True),
    sa.Column('mean_return', sa.Float(), nullable=True),
    sa.Column('median_return', sa.Float(), nullable=True),
    sa.Column('std_return', sa.Float(), nullable=True),
    sa.Column('expectancy_unconditional', sa.Float(), nullable=True),
    sa.Column('sharpe_like', sa.Float(), nullable=True),
    sa.Column('mean_mae', sa.Float(), nullable=True),
    sa.Column('worst_mae', sa.Float(), nullable=True),
    sa.Column('mean_excess_return', sa.Float(), nullable=True),
    sa.Column('median_excess_return', sa.Float(), nullable=True),
    sa.Column('excess_hit_rate', sa.Float(), nullable=True),
    sa.Column('evaluator_version', sa.String(length=32), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('creator_id', 'window_label', 'horizon', 'evaluator_version', name='uq_scorecard_creator_window_horizon_evaluator')
    )
    with op.batch_alter_table('creator_scorecards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_creator_scorecards_creator_id'), ['creator_id'], unique=False)
        batch_op.create_index('ix_scorecard_creator_window', ['creator_id', 'window_label'], unique=False)

    op.create_table('source_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('handle', sa.String(length=128), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_type', 'external_id', name='uq_source_channel_external')
    )
    with op.batch_alter_table('source_channels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_channels_creator_id'), ['creator_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_channel_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('raw_text_path', sa.String(length=512), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_channel_id'], ['source_channels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_type', 'external_id', name='uq_document_external')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_posted_at'), ['posted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_source_channel_id'), ['source_channel_id'], unique=False)

    op.create_table('transcript_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('start_seconds', sa.Float(), nullable=False),
    sa.Column('end_seconds', sa.Float(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('speaker_label', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transcript_segments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transcript_segments_document_id'), ['document_id'], unique=False)

    op.create_table('claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('primary_segment_id', sa.Integer(), nullable=True),
    sa.Column('claim_type', sa.String(length=32), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=True),
    sa.Column('sector', sa.String(length=64), nullable=True),
    sa.Column('polarity', sa.String(length=16), nullable=False),
    sa.Column('claim_class', sa.String(length=16), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('evidence_quote', sa.Text(), nullable=False),
    sa.Column('context_text', sa.Text(), nullable=True),
    sa.Column('context_start_seconds', sa.Float(), nullable=True),
    sa.Column('context_end_seconds', sa.Float(), nullable=True),
    sa.Column('resolution_target_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_outcome', sa.String(length=32), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extractor_version', sa.String(length=32), nullable=False),
    sa.Column('llm_confidence', sa.Float(), nullable=True),
    sa.Column('rule_confidence', sa.Float(), nullable=True),
    sa.Column('final_confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('validator_notes', sa.Text(), nullable=True),
    sa.Column('manual_status', sa.String(length=32), nullable=False),
    sa.Column('manual_notes', sa.Text(), nullable=True),
    sa.Column('manual_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['primary_segment_id'], ['transcript_segments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claims_claim_type'), ['claim_type'], unique=False)
        batch_op.create_index('ix_claims_doc_ticker', ['document_id', 'ticker'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_final_confidence'), ['final_confidence'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_manual_status'), ['manual_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_status'), ['status'], unique=False)
        batch_op.create_index('ix_claims_status_conf', ['status', 'final_confidence'], unique=False)
        batch_op.create_index('ix_claims_type_polarity', ['claim_type', 'polarity'], unique=False)

    op.create_table('extracted_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('primary_segment_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('entry_type', sa.String(length=32), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('stop_price', sa.Float(), nullable=True),
    sa.Column('timeframe', sa.String(length=16), nullable=False),
    sa.Column('reasoning_summary', sa.Text(), nullable=True),
    sa.Column('evidence_quote', sa.Text(), nullable=True),
    sa.Column('context_text', sa.Text(), nullable=True),
    sa.Column('context_start_seconds', sa.Float(), nullable=True),
    sa.Column('context_end_seconds', sa.Float(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extractor_version', sa.String(length=32), nullable=False),
    sa.Column('llm_confidence', sa.Float(), nullable=True),
    sa.Column('rule_confidence', sa.Float(), nullable=True),
    sa.Column('final_confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('validator_notes', sa.Text(), nullable=True),
    sa.Column('manual_status', sa.String(length=32), nullable=False),
    sa.Column('manual_notes', sa.Text(), nullable=True),
    sa.Column('manual_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['primary_segment_id'], ['transcript_segments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extracted_calls', schema=None) as batch_op:
        batch_op.create_index('ix_calls_doc_ticker', ['document_id', 'ticker'], unique=False)
        batch_op.create_index('ix_calls_status_conf', ['status', 'final_confidence'], unique=False)
        batch_op.create_index(batch_op.f('ix_extracted_calls_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_extracted_calls_final_confidence'), ['final_confidence'], unique=False)
        batch_op.create_index(batch_op.f('ix_extracted_calls_manual_status'), ['manual_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_extracted_calls_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_extracted_calls_ticker'), ['ticker'], unique=False)

    op.create_table('gold_labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_key', sa.String(length=64), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('origin_call_id', sa.Integer(), nullable=True),
    sa.Column('origin_document_id', sa.Integer(), nullable=True),
    sa.Column('expected_is_call', sa.Boolean(), nullable=False),
    sa.Column('expected_ticker', sa.String(length=16), nullable=True),
    sa.Column('expected_direction', sa.String(length=16), nullable=True),
    sa.Column('expected_entry_type', sa.String(length=32), nullable=True),
    sa.Column('expected_entry_price', sa.Float(), nullable=True),
    sa.Column('expected_target_price', sa.Float(), nullable=True),
    sa.Column('expected_stop_price', sa.Float(), nullable=True),
    sa.Column('expected_timeframe', sa.String(length=16), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['origin_call_id'], ['extracted_calls.id'], ),
    sa.ForeignKeyConstraint(['origin_document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_key', name='uq_gold_source_key')
    )
    op.create_table('outcome_windows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('horizon', sa.String(length=8), nullable=False),
    sa.Column('window_start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('activated', sa.Boolean(), nullable=False),
    sa.Column('activation_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entry_fill_price', sa.Float(), nullable=True),
    sa.Column('exit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('gross_return_pct', sa.Float(), nullable=True),
    sa.Column('return_pct', sa.Float(), nullable=True),
    sa.Column('mfe', sa.Float(), nullable=True),
    sa.Column('mae', sa.Float(), nullable=True),
    sa.Column('hit_target', sa.Boolean(), nullable=True),
    sa.Column('hit_stop', sa.Boolean(), nullable=True),
    sa.Column('benchmark_return_pct', sa.Float(), nullable=True),
    sa.Column('excess_return_pct', sa.Float(), nullable=True),
    sa.Column('assumptions_cost_bps', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('evaluator_version', sa.String(length=32), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['extracted_calls.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_id', 'horizon', 'evaluator_version', name='uq_outcome_call_horizon_evaluator')
    )
    with op.batch_alter_table('outcome_windows', schema=None) as batch_op:
        batch_op.create_index('ix_outcome_call_horizon', ['call_id', 'horizon'], unique=False)
        batch_op.create_index(batch_op.f('ix_outcome_windows_call_id'), ['call_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outcome_windows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outcome_windows_call_id'))
        batch_op.drop_index('ix_outcome_call_horizon')

    op.drop_table('outcome_windows')
    op.drop_table('gold_labels')
    with op.batch_alter_table('extracted_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extracted_calls_ticker'))
        batch_op.drop_index(batch_op.f('ix_extracted_calls_status'))
        batch_op.drop_index(batch_op.f('ix_extracted_calls_manual_status'))
        batch_op.drop_index(batch_op.f('ix_extracted_calls_final_confidence'))
        batch_op.drop_index(batch_op.f('ix_extracted_calls_document_id'))
        batch_op.drop_index('ix_calls_status_conf')
        batch_op.drop_index('ix_calls_doc_ticker')

    op.drop_table('extracted_calls')
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_index('ix_claims_type_polarity')
        batch_op.drop_index('ix_claims_status_conf')
        batch_op.drop_index(batch_op.f('ix_claims_status'))
        batch_op.drop_index(batch_op.f('ix_claims_manual_status'))
        batch_op.drop_index(batch_op.f('ix_claims_final_confidence'))
        batch_op.drop_index(batch_op.f('ix_claims_document_id'))
        batch_op.drop_index('ix_claims_doc_ticker')
        batch_op.drop_index(batch_op.f('ix_claims_claim_type'))

    op.drop_table('claims')
    with op.batch_alter_table('transcript_segments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transcript_segments_document_id'))

    op.drop_table('transcript_segments')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_source_channel_id'))
        batch_op.drop_index(batch_op.f('ix_documents_posted_at'))

    op.drop_table('documents')
    with op.batch_alter_table('source_channels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_channels_creator_id'))

    op.drop_table('source_channels')
    with op.batch_alter_table('creator_scorecards', schema=None) as batch_op:
        batch_op.drop_index('ix_scorecard_creator_window')
        batch_op.drop_index(batch_op.f('ix_creator_scorecards_creator_id'))

    op.drop_table('creator_scorecards')
    op.drop_table('watchlist')
    with op.batch_alter_table('walkforward_results', schema=None) as batch_op:
        batch_op.drop_index('ix_walkforward_strategy')

    op.drop_table('walkforward_results')
    with op.batch_alter_table('ticker_signals', schema=None) as batch_op:
        batch_op.drop_index('ix_ticker_signal_type_window')
        batch_op.drop_index('ix_ticker_signal_lookup')

    op.drop_table('ticker_signals')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index('ix_tag_label')
        batch_op.drop_index('ix_tag_entity')

    op.drop_table('tags')
    with op.batch_alter_table('research_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_research_snapshot_ticker_time')
        batch_op.drop_index('ix_research_snapshot_status')

    op.drop_table('research_snapshots')
    with op.batch_alter_table('research_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_plans_ticker'))
        batch_op.drop_index('ix_research_plan_ticker_mode_day')

    op.drop_table('research_plans')
    with op.batch_alter_table('market_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_snapshot_ticker_at')

    op.drop_table('market_snapshots')
    op.drop_table('creators')
    with op.batch_alter_table('annotations', schema=None) as batch_op:
        batch_op.drop_index('ix_annotation_entity')

    op.drop_table('annotations')
    # ### end Alembic commands ###
